# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fl', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('filename', models.CharField(default='', max_length=100)),
                ('is_sl', models.BooleanField(default=False)),
                ('sl', models.BooleanField()),
                ('dj', models.CharField(max_length=10)),
                ('zxr', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sug',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('jf', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='sug',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
